version: '3.8'

services:
  app:
    build: .
    environment:
      - name=value
    ports:
      - "8000:8000"
    volumes:
      - iq:/app
    networks:
      - bridge-net
      - iq-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - iq-net

volumes:
  iq:

networks:
  bridge-net:
    driver: bridge
  iq-net:
    name: iq-net