apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: iqimran/python-app:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000   # adjust to your app's port
          env:
          - name: SECRET_KEY
            value: "helloworld"
          - name: DEBUG
            value: "True"
          - name: ALLOWED_HOSTS
          value: "*"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
