apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - name: http
      port: 80
      targetPort: 8000   # match containerPort
      nodePort: 30080    # optional; must be within 30000–32767
